# Preliminares

### Inversa

>Función `solve(A)` en R.

Considerar la matriz cuadrada $A_{p\times p}$. Sea la matriz cuadrada $B_{p\times p}$ una matriz con la propiedad de $AB = I = BA$. En este caso, $B_{p\times p}$ es llamada _la inversa_ de $A$, y se denota como $A^{-1}$. La matrix $I$ es una matriz especial cuyas diagonales son 1, y por encima y debajo de las diagonales solo hay 0s.

$$
  I_{p\times p}= \begin{bmatrix}
  1 & 0 & 0 & \cdots & 0\\
  0 & 1 & 0  & \cdots & 0 \\
  0 & 0 & 1 & \cdots & 0 \\
  \vdots & \vdots & \vdots & \ddots & \vdots \\
  0 & 0 & 0 & \cdots & 1
  \end{bmatrix}
$$

Considerar las matrices

$$
  A = \begin{bmatrix}
  a_{11} & a_{12} \\
  a_{21} & a_{22}
  \end{bmatrix}\quad
  A' = \begin{bmatrix}
  a_{22} & -a_{12} \\
  -a_{21} & a_{11}
  \end{bmatrix}
$$

El producto de ambas es

$$
  AA' = \begin{bmatrix}
    a_{11}a_{22} - a_{12}a_{21} & 0 \\
    0 & a_{11}a_{22} - a_{12}a_{21}
  \end{bmatrix} = (a_{11}a_{22} - a_{12}a_{21})I
$$

Dado que $AA^{-1} = I$, entonces

$$
  A^{-1} = \frac{1}{a_{11}a_{22} - a_{12}a_{21}}A' = \frac{1}{a_{11}a_{22} - a_{12}a_{21}}\begin{bmatrix}
  a_{22} & -a_{12} \\
  -a_{21} & a_{11}
  \end{bmatrix} \tag{1}
$$

**Nota**: para que $A^{-1}$ exista, es decir, para que $A$ sea _invertible_, $a_{11}a_{22} - a_{12}a_{21} \neq 0$.


### Determinante
> Función `det(A)` en R.

Los determinantes solo están definidos para matrices cuadradas $A_{p\times p}$ (matrices que tienen el mismo número de filas que de columnas). El determinante $\text{det}(A)$ o $|A|$ es una función que mapea $A$ a números reales.

De la sección [Inversa](#inversa), sabemos que para una matriz de $2\times 2$, $A^{-1}$ existe si y solo si $a_{11}a_{22} - a_{12}a_{21} \neq 0$. Esta cantidad es el determinante de $A\in \mathbb{R}^{2\times 2}$, es decir

$$
  \text{det}(A)_{2\times 2} = a_{11}a_{22} - a_{12}a_{21}\tag{2}
$$

**Nota**: Tanto en [Inversa](#inversa) como en [Determinante](#determinante) se usó un ejemplo de una matriz sencilla de $2\times 2$. En general, para cualquier matriz $A_{p\times p}$, para que $A^{-1}$ exista, $\text{det}(A_{p\times p})\neq 0$. Es decir, _una matriz cuadrada es invertible **si y solo si** su determinante es diferente de 0._

Se da ahora una expresión general para obtener el determinante de cualquier matriz cuadrada. Sea $A$ la matriz cuadrada ${p\times p}$. Para todo $j=1, \dots, p$, el determinante expandido a través de la fila $j$ se obtiene con

$$
  \text{det}(A) = |A| = \sum_{k=1}^{p}(-1)^{k+j}a_{jk}\text{det}(A_{j,k}) \tag{3}
$$

En donde $A_{j,k}\in \mathbb{R}^{(p-1)\times (p-1)}$ es una _submatriz_ que obtenemos eliminando la fila $j$ y la columna $k$, y $a_{jk}$ es la entrada de la matriz $A$ en la fila $j$ y columna $k$. A la ecuación (2) se le conoce como la expansión de Laplace.

Por ejemplo

$$
  A = \begin{bmatrix}
  1 & 2 & 3\\
  3 & 1 & 2\\
  0 & 0 & 1
  \end{bmatrix}
$$

Usando la expansión de Laplace a en la primera fila, aplicando (2) obtenemos

$$
  |A| = \begin{vmatrix}
  1 & 2 & 3\\
  3 & 1 & 2\\
  0 & 0 & 1
  \end{vmatrix} = %
  \underbrace{(-1)^{1+1}\times 1 \begin{vmatrix}
  1 & 2\\
  0 & 1
  \end{vmatrix}}_{k=1} %
  + \underbrace{(-1)^{1+2}\times 2\begin{vmatrix}
  3 & 2\\
  0 & 1
  \end{vmatrix}}_{k=2} %
    + \underbrace{(-1)^{1+3}\times 3\begin{vmatrix}
  3 & 1\\
  0 & 0
  \end{vmatrix}}_{k=3}
$$

Podemos ahora calcular los determinantes $2\times 2$ usando la ecuación (2). Por ejemplo,

$$
  \begin{vmatrix}
  1 & 2\\
  0 & 1
  \end{vmatrix} = 1\times 1 - 0\times 2 = 1-0
$$

Con lo que tenemos al final $\text{det}(A) = -5$.


En `R`

In [1]:
A <- matrix(
  c(
    1, 2, 3,
    3, 1, 2,
    0, 0, 1
  ),
  byrow = TRUE, # especificar que el orden sea por fila de 3 en 3
  ncol = 3
)
# el determinante
det(A)
# la inversa se obtiene con
solve(A)

[1] -5

[,1] [,2] [,3]
[1,] -0.2  0.4 -0.2
[2,]  0.6 -0.2 -1.4
[3,]  0.0  0.0  1.0

### Núcleo (kernel o espacio nulo)

Considerar la siguiente ecuación

$$
  A \mathbf{x} = \mathbf{0}
$$

El kernel $\text{ker}(A\mathbf{x})$ captura todas las posibles combinaciones lineales $a_1x_1 + \dots + a_px_p$ que producen $\mathbf{0}$. En ese sentido, el kernel es un subespacio de soluciones para $A \mathbf{x} = \mathbf{0}$.


### Eigenvalores y eigenvectores
> Función `eigen(A)` en R.

Considerar la matriz cuadrada $A_{p\times p}$. Si existe un escalar $\lambda$ y un vector $\mathbf{x}$ tal que

$$
  A\mathbf{x} = \lambda\mathbf{x} \tag{4}
$$

La ecuación (3) es llamada _la ecuación de eigenvalores_. $\lambda$ es un _eigenvalor_ (valor propio) y $\mathbf{x}$ un eigenvector.

Un eigenvalor $\lambda$ es la raíz del polinomio de orden $p$,

$$
  (A - \lambda I)\mathbf{x}=\mathbf{0} \tag{5}
$$

por lo que hay $p$ eigenvalores de $A$. A cada eigenvalor $\lambda_j$ le corresponde un eigenvector $x_j$. Dado que $\mathbf{x} \neq \mathbf{0}$, la ecuación (4) implica que $(A - \lambda I) =\mathbf{0}$, y el kernel $\text{ker}(A - \lambda I)$ debe contener más elementos que no sean $\mathbf{0}$, es decir $x \in \text{ker}(A-\lambda I)$, por lo que la matriz no es invertible y su determinante es 0, es decir

$$
  \text{det}(A - \lambda I) = 0 \tag{6}
$$

A la ecuación (5) se le conoce como _polinomio característico_. En la matriz

$$
  A = \begin{bmatrix}
  4 & 2 \\
  1 & 3
  \end{bmatrix}
$$

Su polinomio característico es

$$
p_A(\lambda) = \text{det}(A - \lambda I) = \text{det} %
\left( %
\begin{bmatrix}
  4 & 2 \\
  1 & 3
\end{bmatrix} - %
\begin{bmatrix}
  \lambda & 0 \\
  0 & \lambda
\end{bmatrix}
\right) =
\begin{vmatrix}
  4 - \lambda & 2 \\
  1           & 3 - \lambda
\end{vmatrix}
$$

Que se reduce a

$$
  p_A(\lambda) = (4 - \lambda)(3 - \lambda) - 2 = 0
$$

Y factorizando

$$
  p_A(\lambda) = (2 - \lambda)(5 - \lambda) = 0
$$

Cuyas soluciones son $\lambda_1 = 2, \lambda_2 = 5$.

Los eigenvectores se pueden encontrar sustituyendo los eigenvalores en

$$
  \begin{bmatrix}
  4 - \lambda & 2 \\
  1           & 3 - \lambda
\end{bmatrix}\mathbf{x} = \mathbf{0}
$$

**Nota**: el determinante de $A$ es el producto de sus eigenvalores

$$
  \text{det}(A) = \prod_{i=1}^n \lambda_i
$$

> TL;DR: los eigen valores se pueden obtener resolviendo la ecuación $\det(A-\lambda I)=0$ y despejando para $\lambda$.
> O usando `eigen(A)$values` en R. Se ilustra a continuación

In [2]:
# Nota: c(4, 2, 1, 3) produce un vector; ncol especifica cuántas columnas,
# por lo que el número de filas se calcula en automático como length/ncol.
# byrow = TRUE indica que los datos se acomoden por filas rellenando las columnas.
A <- matrix(c(4, 2, 1, 3), ncol = 2, byrow = TRUE)
A
eigen(A)$values

[,1] [,2]
[1,] 4    2   
[2,] 1    3

[1] 5 2

### Descomposición espectral

La matriz cuadrada $A_{p\times p}$ puede se reescrita como

$$
  A = \mathbf{P} D \mathbf{P}^{-1} \tag{7}
$$

En donde la matriz diagonal $D = \text{diag}(\lambda_1, \lambda_2,\dots,\lambda_p)$.

**Nota**: Cuando $A$ es simétrica, $\mathbf{P}$ es ortogonal, lo que significa que $\mathbf{P}\mathbf{P}^\top=\mathbf{P}\mathbf{P}^{-1}=I$, o lo que es lo mismo, $\mathbf{P}^\top=\mathbf{P}^{-1}$, por lo que

$$
  A = \mathbf{P} D \mathbf{P}^\top
$$

### Matrices triangulares y factorización de Cholesky

Una matriz simétrica definida positiva $A \in \mathbb{R}^{p\times p}$ puede ser factorizada como el producto 

$$A = LL^\top$$

En donde $L$ es la matriz triangular inferior, una matriz cuadrada especial cuyas entradas por encima de la diagonal son 0s.

$$
  L = \begin{bmatrix}
    l_{11} & 0 & \cdots & \cdots & 0 \\
    l_{12} & l_{22} & \ddots &  & \vdots\\
    \vdots & \ddots & \ddots & \ddots & \vdots\\
    \vdots &  & \ddots & \ddots & 0\\
    l_{1p} & \cdots & \cdots & l_{p-1p} & l_{pp}
\end{bmatrix}
$$

En `R` se obtiene con la función `chol()`.

In [3]:
## eigenvalores y descomposición espectral
# Crear A
A <- matrix(
  data = c(-3, 4, 5, -2),
  nrow = 2
)

# eigenvalores y eigenvectores usando la función eigen(), ?eigen para ayuda
# retorna un objeto de dos elementos: los eigenvalores y los eigenvectores
eig <- eigen(A) # desc. espectral

# crear P
P <- eig$vectors

# crear la diagonal de eigenvalores D
D <- diag(eig$values)
# verificar eq 7; la inversa de P se obtiene con solve(P)
list(
  APDP = P %*% D %*% solve(P),
  A = A
)


$APDP
     [,1] [,2]
[1,]   -3    5
[2,]    4   -2

$A
     [,1] [,2]
[1,]   -3    5
[2,]    4   -2

In [4]:
# determinante es igual al producto de los eigenvalores
det(A)
prod(eig$values)

[1] -14

[1] -14

In [5]:
# Ahora verificamos que si A es simétrica, P es ortogonal
# A simétrica
A <- matrix(
  data = c(1, 4, 2, 4, 1, 3, 2, 3, 1),
  nrow = 3
)
eig <- eigen(A)
# P
P <- eig$vectors
# Inversa de P
solve(P)
# transpuesta de P
t(P)

A # A es igual al producto PDP'
P %*% diag(eig$values) %*% t(P)

[,1]       [,2]       [,3]      
[1,] -0.5843738 -0.6345775 -0.5057852
[2,]  0.5449251  0.1549789 -0.8240377
[3,]  0.6013018 -0.7571611  0.2552315

[,1]       [,2]       [,3]      
[1,] -0.5843738 -0.6345775 -0.5057852
[2,]  0.5449251  0.1549789 -0.8240377
[3,]  0.6013018 -0.7571611  0.2552315

[,1] [,2] [,3]
[1,] 1    4    2   
[2,] 4    1    3   
[3,] 2    3    1

[,1] [,2] [,3]
[1,] 1    4    2   
[2,] 4    1    3   
[3,] 2    3    1